language: haxe

# TravisCI by default run on linux.
# Let's enable both linux and mac builds because why not?
os:
  - windows
  - linux
  - osx

dist: bionic

env:
  global:
    - HOMEBREW_NO_INSTALL_CLEANUP=1

# Test with Haxe 4.0.2 and Haxe development.
haxe:
  - "4.0.2"
  - "3.4.7"
  - development

matrix:
  # Allow Haxe development to fail.
  allow_failures:
    - haxe: development

addons:
  # This is the preferred way to install apt packages.
  # However, it only allow some but not all packages.
  # Alternatively, we can use `sudo apt-get install ...` in the `install:` section.
  # http://docs.travis-ci.com/user/apt/#Adding-APT-Packages
  apt:
    packages:
      # C++ (for rebuilding hxcpp)
      - gcc-multilib
      - g++-multilib
      # Python
      - python3
      # PHP
      - php-cli
      - php-mbstring
      # C#
      - mono-devel
      - mono-mcs
      # Flash
      - libglib2.0
      - libfreetype6
      # Lua
      - cmake
      - lua5.1
      - luarocks
      - libpcre3-dev
      - libssl-dev

install:
  # os-specific config
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export DISPLAY=:99.0;
      export AUDIODEV=null;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
      brew cask uninstall oclint;
      brew install mono;
      brew upgrade python;
      brew install lua pcre;
      brew install luarocks --HEAD;
    elif [ "${TRAVIS_OS_NAME}" = "windows" ]; then
      choco install nodejs --version 11.5.0 -y; export PATH="/c/Program Files/nodejs:$PATH";
      choco install openjdk --version 11.0.1 -y; export PATH="/c/Program Files/OpenJDK/jdk-11.0.1/bin:$PATH";
      choco install php --version 7.4.0 -y; export PATH="/c/tools/php74:$PATH"; sed -i 's/;extension_dir = "ext"/extension_dir = "ext"/; s/;extension=mbstring/extension=mbstring/' "/c/tools/php74/php.ini";
      choco install python --version 3.7.1 -y; export PATH="/c/Python37/Scripts:/c/Python37:$PATH";
    fi
  # Haxe Lua dependencies
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo luarocks install haxe-deps;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      sudo luarocks install haxe-deps;
    elif [ "${TRAVIS_OS_NAME}" = "windows" ]; then
      pip install hererocks;
      hererocks luaenv --lua 5.3 -rlatest;
      export PATH="$(pwd)/luaenv/bin:$PATH";
    fi
  # Download and setup a standalone flash player debugger
  - haxe flash/install.hxml
  # Install haxelibs
  - if [ "${TRAVIS_HAXE_VERSION}" = "development" ]; then
      haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git;
      pushd $(haxelib path hxcpp | head -1);
        pushd tools/hxcpp; haxe compile.hxml; popd;
        pushd project; neko build.n; popd;
      popd;
    else
      haxelib install hxcpp;
    fi
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib list

script:
  - haxe build-interp.hxml
  - haxe build-neko.hxml         && neko bin/HelloWorld.n
  - haxe build-js.hxml           && node bin/HelloWorld.js
  - haxe build-java.hxml         && java -jar bin/HelloWorld.jar
  - haxe build-php.hxml          && php bin/index.php
  - haxe build-cs.hxml           && ( if [ "${TRAVIS_OS_NAME}" = "windows" ]; then bin/bin/HelloWorld.exe; else mono bin/bin/HelloWorld.exe; fi )
  - haxe build-flash.hxml -D fdb && haxe flash/run.hxml bin/HelloWorld.swf
  - haxe build-cpp.hxml          && ./bin/HelloWorld
  - haxe build-python.hxml       && ( if [ "${TRAVIS_OS_NAME}" = "windows" ]; then python bin/HelloWorld.py; else python3 bin/HelloWorld.py; fi )
  - haxe build-lua.hxml          && lua bin/HelloWorld.lua
