stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        container: haxe:3.4.7
        steps:
          - script: haxe build-neko.hxml
            displayName: 'Compile'
          - task: PublishPipelineArtifact@0
            inputs:
              artifactName: 'nekoOutput'
              targetPath: bin/HelloWorld.n

  - stage: Test
    jobs:
      - job: TestMacro
        pool:
          vmImage: 'ubuntu-latest'
        container: haxe:3.4.7
        steps:
          - script: haxe build-interp.hxml
            displayName: 'Test'

      - job: TestNekoLinux
        pool:
          vmImage: 'ubuntu-latest'
        container: haxe:3.4.7
        steps:
          - task: DownloadPipelineArtifact@0
            inputs:
              artifactName: 'nekoOutput'
              targetPath: bin
          - script: neko bin/HelloWorld.n
            displayName: 'Test'

      - job: TestNekoMac
        pool:
          vmImage: 'macOS-10.14'
        steps:
          - script: |
              brew install neko
            displayName: 'Install Neko'
          - task: DownloadPipelineArtifact@0
            inputs:
              artifactName: 'nekoOutput'
              targetPath: bin
          - script: neko bin/HelloWorld.n
            displayName: 'Test'

      - job: TestNekoWindows
        pool:
          vmImage: 'windows-2019'
        steps:
          - script: |
              choco install neko -y
            displayName: 'Install Neko'
          - task: DownloadPipelineArtifact@0
            inputs:
              artifactName: 'nekoOutput'
              targetPath: bin
          - script: neko bin/HelloWorld.n
            displayName: 'Test'
