# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo add-apt-repository ppa:haxe/releases -y
    sudo apt update -y
    sudo apt install haxe -y
  displayName: 'Install Haxe'

- script: |
    haxe build-interp.hxml
  displayName: 'Test macro target'
